name: Reusable NEAR WASM

on:
  workflow_call:
    inputs:
      config_hash:
        required: true
        type: string

env:
  FORCE_COLOR: 1

jobs:
  build-wasi-reusable:
    name: 'build and test'
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    env:
      WASMTIME_VERSION: 22.0.0
      EMSCRIPTEN_VERSION: 4.0.10
      EMSDK_PATH: /opt/emsdk
      CROSS_BUILD_PYTHON: builddir/build
      CROSS_BUILD_EMSCRIPTEN_NEAR: builddir/emscripten-near
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Cache Emscripten
      id: cache-emsdk
      uses: actions/cache@v4
      with:
        path: ${{ env.EMSDK_PATH }}
        key: ${{ runner.os }}-emsdk-${{ env.EMSCRIPTEN_VERSION }}
        restore-keys: |
          ${{ runner.os }}-emsdk-${{ env.EMSCRIPTEN_VERSION }}
    - name: Install Emscripten
      if: steps.cache-emsdk.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/emscripten-core/emsdk.git ${{ env.EMSDK_PATH }}
        cd ${{ env.EMSDK_PATH }}
        ./emsdk install 4.0.0
        ./emsdk activate 4.0.0
        source ${{ env.EMSDK_PATH }}/emsdk_env.sh
        echo "$(dirname $(which emcc))" >> $GITHUB_PATH
        echo "EMSDK=${{ env.EMSDK_PATH }}" >> $GITHUB_ENV
        echo "EM_CONFIG=${{ env.EMSDK_PATH }}/.emscripten" >> $GITHUB_ENV
        echo "EMSDK_NODE=${{ env.EMSDK_PATH }}/node/18.20.3_64bit/bin/node" >> $GITHUB_ENV
    - name: "Configure ccache action"
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        save: ${{ github.event_name == 'push' }}
        max-size: "200M"
    - name: "Add ccache to PATH"
      run: echo "PATH=/usr/lib/ccache:$PATH" >> "$GITHUB_ENV"
    - name: "Install Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: "Runner image version"
      run: echo "IMAGE_OS_VERSION=${ImageOS}-${ImageVersion}" >> "$GITHUB_ENV"
    - name: "Restore Python build config.cache"
      uses: actions/cache@v4
      with:
        path: ${{ env.CROSS_BUILD_PYTHON }}/config.cache
        # Include env.pythonLocation in key to avoid changes in environment when setup-python updates Python.
        # Include the hash of `Tools/wasm/wasi.py` as it may change the environment variables.
        # (Make sure to keep the key in sync with the other config.cache step below.)
        key: ${{ github.job }}-${{ env.IMAGE_OS_VERSION }}-${{ env.EMSCRIPTEN_VERSION }}-${{ inputs.config_hash }}-${{ hashFiles('Tools/wasm/wasm_build.py') }}-${{ env.pythonLocation }}
    - name: "Configure build Python"
      run: python3 Tools/wasm/wasm_build.py emscripten-near configure-build-python -- --config-cache --with-pydebug
    - name: "Make build Python"
      run: python3 Tools/wasm/wasm_build.py emscripten-near make-build-python
    - name: "Restore host config.cache"
      uses: actions/cache@v4
      with:
        path: ${{ env.CROSS_BUILD_EMSCRIPTEN_NEAR }}/config.cache
        # Should be kept in sync with the other config.cache step above.
        key: ${{ github.job }}-${{ env.IMAGE_OS_VERSION }}-${{ env.EMSCRIPTEN_VERSION }}-${{ inputs.config_hash }}-${{ hashFiles('Tools/wasm/wasm_build.py') }}-${{ env.pythonLocation }}
    - name: "Configure host"
      # `--with-pydebug` inferred from configure-build-python
      run: python3 Tools/wasm/wasm_build.py emscripten-near configure-host -- --config-cache
    - name: "Make host"
      run: python3 Tools/wasm/wasm_build.py emscripten-near make-host
    - name: "Display build info"
      run: make --directory "${CROSS_BUILD_EMSCRIPTEN_NEAR}" pythoninfo
    - name: "Upload python.wasm"
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.CROSS_BUILD_EMSCRIPTEN_NEAR }}/python.wasm
        asset_name: python.wasm
        asset_content_type: application/wasm
    - name: "Upload python-stdlib.zip"
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.CROSS_BUILD_EMSCRIPTEN_NEAR }}/python-stdlib.zip
        asset_name: python-stdlib.zip
        asset_content_type: application/zip
    - name: "Test"
      run: make --directory "${CROSS_BUILD_EMSCRIPTEN_NEAR}" test
